// Generated by gencpp from file flexbe_msgs/GetUserdataResponse.msg
// DO NOT EDIT!


#ifndef FLEXBE_MSGS_MESSAGE_GETUSERDATARESPONSE_H
#define FLEXBE_MSGS_MESSAGE_GETUSERDATARESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <flexbe_msgs/UserdataInfo.h>

namespace flexbe_msgs
{
template <class ContainerAllocator>
struct GetUserdataResponse_
{
  typedef GetUserdataResponse_<ContainerAllocator> Type;

  GetUserdataResponse_()
    : success(false)
    , message()
    , userdata()  {
    }
  GetUserdataResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)
    , userdata(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef std::vector< ::flexbe_msgs::UserdataInfo_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::flexbe_msgs::UserdataInfo_<ContainerAllocator> >> _userdata_type;
  _userdata_type userdata;





  typedef boost::shared_ptr< ::flexbe_msgs::GetUserdataResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flexbe_msgs::GetUserdataResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetUserdataResponse_

typedef ::flexbe_msgs::GetUserdataResponse_<std::allocator<void> > GetUserdataResponse;

typedef boost::shared_ptr< ::flexbe_msgs::GetUserdataResponse > GetUserdataResponsePtr;
typedef boost::shared_ptr< ::flexbe_msgs::GetUserdataResponse const> GetUserdataResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::flexbe_msgs::GetUserdataResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::flexbe_msgs::GetUserdataResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::flexbe_msgs::GetUserdataResponse_<ContainerAllocator1> & lhs, const ::flexbe_msgs::GetUserdataResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message &&
    lhs.userdata == rhs.userdata;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::flexbe_msgs::GetUserdataResponse_<ContainerAllocator1> & lhs, const ::flexbe_msgs::GetUserdataResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace flexbe_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::flexbe_msgs::GetUserdataResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flexbe_msgs::GetUserdataResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flexbe_msgs::GetUserdataResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flexbe_msgs::GetUserdataResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flexbe_msgs::GetUserdataResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flexbe_msgs::GetUserdataResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::flexbe_msgs::GetUserdataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9fe01c8c705cb717d6bd6a64a500fdeb";
  }

  static const char* value(const ::flexbe_msgs::GetUserdataResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9fe01c8c705cb717ULL;
  static const uint64_t static_value2 = 0xd6bd6a64a500fdebULL;
};

template<class ContainerAllocator>
struct DataType< ::flexbe_msgs::GetUserdataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "flexbe_msgs/GetUserdataResponse";
  }

  static const char* value(const ::flexbe_msgs::GetUserdataResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::flexbe_msgs::GetUserdataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
"flexbe_msgs/UserdataInfo[] userdata\n"
"\n"
"\n"
"================================================================================\n"
"MSG: flexbe_msgs/UserdataInfo\n"
"string state\n"
"string key\n"
"string type\n"
"string data\n"
;
  }

  static const char* value(const ::flexbe_msgs::GetUserdataResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::flexbe_msgs::GetUserdataResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
      stream.next(m.userdata);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetUserdataResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::flexbe_msgs::GetUserdataResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::flexbe_msgs::GetUserdataResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    s << indent << "userdata[]" << std::endl;
    for (size_t i = 0; i < v.userdata.size(); ++i)
    {
      s << indent << "  userdata[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::flexbe_msgs::UserdataInfo_<ContainerAllocator> >::stream(s, indent + "    ", v.userdata[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLEXBE_MSGS_MESSAGE_GETUSERDATARESPONSE_H
