// Generated by gencpp from file flexbe_msgs/GetUserdataRequest.msg
// DO NOT EDIT!


#ifndef FLEXBE_MSGS_MESSAGE_GETUSERDATAREQUEST_H
#define FLEXBE_MSGS_MESSAGE_GETUSERDATAREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace flexbe_msgs
{
template <class ContainerAllocator>
struct GetUserdataRequest_
{
  typedef GetUserdataRequest_<ContainerAllocator> Type;

  GetUserdataRequest_()
    : userdata_key()  {
    }
  GetUserdataRequest_(const ContainerAllocator& _alloc)
    : userdata_key(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _userdata_key_type;
  _userdata_key_type userdata_key;





  typedef boost::shared_ptr< ::flexbe_msgs::GetUserdataRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flexbe_msgs::GetUserdataRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetUserdataRequest_

typedef ::flexbe_msgs::GetUserdataRequest_<std::allocator<void> > GetUserdataRequest;

typedef boost::shared_ptr< ::flexbe_msgs::GetUserdataRequest > GetUserdataRequestPtr;
typedef boost::shared_ptr< ::flexbe_msgs::GetUserdataRequest const> GetUserdataRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::flexbe_msgs::GetUserdataRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::flexbe_msgs::GetUserdataRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::flexbe_msgs::GetUserdataRequest_<ContainerAllocator1> & lhs, const ::flexbe_msgs::GetUserdataRequest_<ContainerAllocator2> & rhs)
{
  return lhs.userdata_key == rhs.userdata_key;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::flexbe_msgs::GetUserdataRequest_<ContainerAllocator1> & lhs, const ::flexbe_msgs::GetUserdataRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace flexbe_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::flexbe_msgs::GetUserdataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flexbe_msgs::GetUserdataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flexbe_msgs::GetUserdataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flexbe_msgs::GetUserdataRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flexbe_msgs::GetUserdataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flexbe_msgs::GetUserdataRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::flexbe_msgs::GetUserdataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7cdb08bd760006001b7e7e1ce021b490";
  }

  static const char* value(const ::flexbe_msgs::GetUserdataRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7cdb08bd76000600ULL;
  static const uint64_t static_value2 = 0x1b7e7e1ce021b490ULL;
};

template<class ContainerAllocator>
struct DataType< ::flexbe_msgs::GetUserdataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "flexbe_msgs/GetUserdataRequest";
  }

  static const char* value(const ::flexbe_msgs::GetUserdataRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::flexbe_msgs::GetUserdataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# specify key to filter userdata, leave empty to get all userdata\n"
"string userdata_key\n"
;
  }

  static const char* value(const ::flexbe_msgs::GetUserdataRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::flexbe_msgs::GetUserdataRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.userdata_key);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetUserdataRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::flexbe_msgs::GetUserdataRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::flexbe_msgs::GetUserdataRequest_<ContainerAllocator>& v)
  {
    s << indent << "userdata_key: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.userdata_key);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLEXBE_MSGS_MESSAGE_GETUSERDATAREQUEST_H
