// Generated by gencpp from file flexbe_msgs/GetUserdata.msg
// DO NOT EDIT!


#ifndef FLEXBE_MSGS_MESSAGE_GETUSERDATA_H
#define FLEXBE_MSGS_MESSAGE_GETUSERDATA_H

#include <ros/service_traits.h>


#include <flexbe_msgs/GetUserdataRequest.h>
#include <flexbe_msgs/GetUserdataResponse.h>


namespace flexbe_msgs
{

struct GetUserdata
{

typedef GetUserdataRequest Request;
typedef GetUserdataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetUserdata
} // namespace flexbe_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::flexbe_msgs::GetUserdata > {
  static const char* value()
  {
    return "cf480fa533a0ed079b4f74ca618d3d84";
  }

  static const char* value(const ::flexbe_msgs::GetUserdata&) { return value(); }
};

template<>
struct DataType< ::flexbe_msgs::GetUserdata > {
  static const char* value()
  {
    return "flexbe_msgs/GetUserdata";
  }

  static const char* value(const ::flexbe_msgs::GetUserdata&) { return value(); }
};


// service_traits::MD5Sum< ::flexbe_msgs::GetUserdataRequest> should match
// service_traits::MD5Sum< ::flexbe_msgs::GetUserdata >
template<>
struct MD5Sum< ::flexbe_msgs::GetUserdataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::flexbe_msgs::GetUserdata >::value();
  }
  static const char* value(const ::flexbe_msgs::GetUserdataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::flexbe_msgs::GetUserdataRequest> should match
// service_traits::DataType< ::flexbe_msgs::GetUserdata >
template<>
struct DataType< ::flexbe_msgs::GetUserdataRequest>
{
  static const char* value()
  {
    return DataType< ::flexbe_msgs::GetUserdata >::value();
  }
  static const char* value(const ::flexbe_msgs::GetUserdataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::flexbe_msgs::GetUserdataResponse> should match
// service_traits::MD5Sum< ::flexbe_msgs::GetUserdata >
template<>
struct MD5Sum< ::flexbe_msgs::GetUserdataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::flexbe_msgs::GetUserdata >::value();
  }
  static const char* value(const ::flexbe_msgs::GetUserdataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::flexbe_msgs::GetUserdataResponse> should match
// service_traits::DataType< ::flexbe_msgs::GetUserdata >
template<>
struct DataType< ::flexbe_msgs::GetUserdataResponse>
{
  static const char* value()
  {
    return DataType< ::flexbe_msgs::GetUserdata >::value();
  }
  static const char* value(const ::flexbe_msgs::GetUserdataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FLEXBE_MSGS_MESSAGE_GETUSERDATA_H
