// Generated by gencpp from file flexbe_msgs/UserdataInfo.msg
// DO NOT EDIT!


#ifndef FLEXBE_MSGS_MESSAGE_USERDATAINFO_H
#define FLEXBE_MSGS_MESSAGE_USERDATAINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace flexbe_msgs
{
template <class ContainerAllocator>
struct UserdataInfo_
{
  typedef UserdataInfo_<ContainerAllocator> Type;

  UserdataInfo_()
    : state()
    , key()
    , type()
    , data()  {
    }
  UserdataInfo_(const ContainerAllocator& _alloc)
    : state(_alloc)
    , key(_alloc)
    , type(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _state_type;
  _state_type state;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _key_type;
  _key_type key;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _type_type;
  _type_type type;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::flexbe_msgs::UserdataInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::flexbe_msgs::UserdataInfo_<ContainerAllocator> const> ConstPtr;

}; // struct UserdataInfo_

typedef ::flexbe_msgs::UserdataInfo_<std::allocator<void> > UserdataInfo;

typedef boost::shared_ptr< ::flexbe_msgs::UserdataInfo > UserdataInfoPtr;
typedef boost::shared_ptr< ::flexbe_msgs::UserdataInfo const> UserdataInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::flexbe_msgs::UserdataInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::flexbe_msgs::UserdataInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::flexbe_msgs::UserdataInfo_<ContainerAllocator1> & lhs, const ::flexbe_msgs::UserdataInfo_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state &&
    lhs.key == rhs.key &&
    lhs.type == rhs.type &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::flexbe_msgs::UserdataInfo_<ContainerAllocator1> & lhs, const ::flexbe_msgs::UserdataInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace flexbe_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::flexbe_msgs::UserdataInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::flexbe_msgs::UserdataInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flexbe_msgs::UserdataInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::flexbe_msgs::UserdataInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flexbe_msgs::UserdataInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::flexbe_msgs::UserdataInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::flexbe_msgs::UserdataInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1772a03af66e5ec2ab7e8c44750f6721";
  }

  static const char* value(const ::flexbe_msgs::UserdataInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1772a03af66e5ec2ULL;
  static const uint64_t static_value2 = 0xab7e8c44750f6721ULL;
};

template<class ContainerAllocator>
struct DataType< ::flexbe_msgs::UserdataInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "flexbe_msgs/UserdataInfo";
  }

  static const char* value(const ::flexbe_msgs::UserdataInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::flexbe_msgs::UserdataInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string state\n"
"string key\n"
"string type\n"
"string data\n"
;
  }

  static const char* value(const ::flexbe_msgs::UserdataInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::flexbe_msgs::UserdataInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.key);
      stream.next(m.type);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UserdataInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::flexbe_msgs::UserdataInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::flexbe_msgs::UserdataInfo_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.state);
    s << indent << "key: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.key);
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.type);
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FLEXBE_MSGS_MESSAGE_USERDATAINFO_H
