# MoveArm.action

# Goal definition
float64[] joint_positions

---
# Result definition
bool success
float64 difference

---
# Feedback definition
float64 duration
bool plan_success
float64 execution_progress
string stage
