// Generated by gencpp from file mirte_msgs_2/GetDistance.msg
// DO NOT EDIT!


#ifndef MIRTE_MSGS_2_MESSAGE_GETDISTANCE_H
#define MIRTE_MSGS_2_MESSAGE_GETDISTANCE_H

#include <ros/service_traits.h>


#include <mirte_msgs_2/GetDistanceRequest.h>
#include <mirte_msgs_2/GetDistanceResponse.h>


namespace mirte_msgs_2
{

struct GetDistance
{

typedef GetDistanceRequest Request;
typedef GetDistanceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetDistance
} // namespace mirte_msgs_2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mirte_msgs_2::GetDistance > {
  static const char* value()
  {
    return "73fcbf46b49191e672908e50842a83d4";
  }

  static const char* value(const ::mirte_msgs_2::GetDistance&) { return value(); }
};

template<>
struct DataType< ::mirte_msgs_2::GetDistance > {
  static const char* value()
  {
    return "mirte_msgs_2/GetDistance";
  }

  static const char* value(const ::mirte_msgs_2::GetDistance&) { return value(); }
};


// service_traits::MD5Sum< ::mirte_msgs_2::GetDistanceRequest> should match
// service_traits::MD5Sum< ::mirte_msgs_2::GetDistance >
template<>
struct MD5Sum< ::mirte_msgs_2::GetDistanceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs_2::GetDistance >::value();
  }
  static const char* value(const ::mirte_msgs_2::GetDistanceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs_2::GetDistanceRequest> should match
// service_traits::DataType< ::mirte_msgs_2::GetDistance >
template<>
struct DataType< ::mirte_msgs_2::GetDistanceRequest>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs_2::GetDistance >::value();
  }
  static const char* value(const ::mirte_msgs_2::GetDistanceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mirte_msgs_2::GetDistanceResponse> should match
// service_traits::MD5Sum< ::mirte_msgs_2::GetDistance >
template<>
struct MD5Sum< ::mirte_msgs_2::GetDistanceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs_2::GetDistance >::value();
  }
  static const char* value(const ::mirte_msgs_2::GetDistanceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs_2::GetDistanceResponse> should match
// service_traits::DataType< ::mirte_msgs_2::GetDistance >
template<>
struct DataType< ::mirte_msgs_2::GetDistanceResponse>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs_2::GetDistance >::value();
  }
  static const char* value(const ::mirte_msgs_2::GetDistanceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MIRTE_MSGS_2_MESSAGE_GETDISTANCE_H
