// Generated by gencpp from file mirte_msgs_2/GetEncoder.msg
// DO NOT EDIT!


#ifndef MIRTE_MSGS_2_MESSAGE_GETENCODER_H
#define MIRTE_MSGS_2_MESSAGE_GETENCODER_H

#include <ros/service_traits.h>


#include <mirte_msgs_2/GetEncoderRequest.h>
#include <mirte_msgs_2/GetEncoderResponse.h>


namespace mirte_msgs_2
{

struct GetEncoder
{

typedef GetEncoderRequest Request;
typedef GetEncoderResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetEncoder
} // namespace mirte_msgs_2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mirte_msgs_2::GetEncoder > {
  static const char* value()
  {
    return "da5909fbe378aeaf85e547e830cc1bb7";
  }

  static const char* value(const ::mirte_msgs_2::GetEncoder&) { return value(); }
};

template<>
struct DataType< ::mirte_msgs_2::GetEncoder > {
  static const char* value()
  {
    return "mirte_msgs_2/GetEncoder";
  }

  static const char* value(const ::mirte_msgs_2::GetEncoder&) { return value(); }
};


// service_traits::MD5Sum< ::mirte_msgs_2::GetEncoderRequest> should match
// service_traits::MD5Sum< ::mirte_msgs_2::GetEncoder >
template<>
struct MD5Sum< ::mirte_msgs_2::GetEncoderRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs_2::GetEncoder >::value();
  }
  static const char* value(const ::mirte_msgs_2::GetEncoderRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs_2::GetEncoderRequest> should match
// service_traits::DataType< ::mirte_msgs_2::GetEncoder >
template<>
struct DataType< ::mirte_msgs_2::GetEncoderRequest>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs_2::GetEncoder >::value();
  }
  static const char* value(const ::mirte_msgs_2::GetEncoderRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mirte_msgs_2::GetEncoderResponse> should match
// service_traits::MD5Sum< ::mirte_msgs_2::GetEncoder >
template<>
struct MD5Sum< ::mirte_msgs_2::GetEncoderResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs_2::GetEncoder >::value();
  }
  static const char* value(const ::mirte_msgs_2::GetEncoderResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs_2::GetEncoderResponse> should match
// service_traits::DataType< ::mirte_msgs_2::GetEncoder >
template<>
struct DataType< ::mirte_msgs_2::GetEncoderResponse>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs_2::GetEncoder >::value();
  }
  static const char* value(const ::mirte_msgs_2::GetEncoderResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MIRTE_MSGS_2_MESSAGE_GETENCODER_H
