// Generated by gencpp from file mirte_msgs_2/GetIMU.msg
// DO NOT EDIT!


#ifndef MIRTE_MSGS_2_MESSAGE_GETIMU_H
#define MIRTE_MSGS_2_MESSAGE_GETIMU_H

#include <ros/service_traits.h>


#include <mirte_msgs_2/GetIMURequest.h>
#include <mirte_msgs_2/GetIMUResponse.h>


namespace mirte_msgs_2
{

struct GetIMU
{

typedef GetIMURequest Request;
typedef GetIMUResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetIMU
} // namespace mirte_msgs_2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mirte_msgs_2::GetIMU > {
  static const char* value()
  {
    return "1a90e9316c538a225459520b61aa5e33";
  }

  static const char* value(const ::mirte_msgs_2::GetIMU&) { return value(); }
};

template<>
struct DataType< ::mirte_msgs_2::GetIMU > {
  static const char* value()
  {
    return "mirte_msgs_2/GetIMU";
  }

  static const char* value(const ::mirte_msgs_2::GetIMU&) { return value(); }
};


// service_traits::MD5Sum< ::mirte_msgs_2::GetIMURequest> should match
// service_traits::MD5Sum< ::mirte_msgs_2::GetIMU >
template<>
struct MD5Sum< ::mirte_msgs_2::GetIMURequest>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs_2::GetIMU >::value();
  }
  static const char* value(const ::mirte_msgs_2::GetIMURequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs_2::GetIMURequest> should match
// service_traits::DataType< ::mirte_msgs_2::GetIMU >
template<>
struct DataType< ::mirte_msgs_2::GetIMURequest>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs_2::GetIMU >::value();
  }
  static const char* value(const ::mirte_msgs_2::GetIMURequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mirte_msgs_2::GetIMUResponse> should match
// service_traits::MD5Sum< ::mirte_msgs_2::GetIMU >
template<>
struct MD5Sum< ::mirte_msgs_2::GetIMUResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs_2::GetIMU >::value();
  }
  static const char* value(const ::mirte_msgs_2::GetIMUResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs_2::GetIMUResponse> should match
// service_traits::DataType< ::mirte_msgs_2::GetIMU >
template<>
struct DataType< ::mirte_msgs_2::GetIMUResponse>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs_2::GetIMU >::value();
  }
  static const char* value(const ::mirte_msgs_2::GetIMUResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MIRTE_MSGS_2_MESSAGE_GETIMU_H
