// Generated by gencpp from file mirte_msgs_2/GetKeypad.msg
// DO NOT EDIT!


#ifndef MIRTE_MSGS_2_MESSAGE_GETKEYPAD_H
#define MIRTE_MSGS_2_MESSAGE_GETKEYPAD_H

#include <ros/service_traits.h>


#include <mirte_msgs_2/GetKeypadRequest.h>
#include <mirte_msgs_2/GetKeypadResponse.h>


namespace mirte_msgs_2
{

struct GetKeypad
{

typedef GetKeypadRequest Request;
typedef GetKeypadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetKeypad
} // namespace mirte_msgs_2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mirte_msgs_2::GetKeypad > {
  static const char* value()
  {
    return "992ce8a1687cec8c8bd883ec73ca41d1";
  }

  static const char* value(const ::mirte_msgs_2::GetKeypad&) { return value(); }
};

template<>
struct DataType< ::mirte_msgs_2::GetKeypad > {
  static const char* value()
  {
    return "mirte_msgs_2/GetKeypad";
  }

  static const char* value(const ::mirte_msgs_2::GetKeypad&) { return value(); }
};


// service_traits::MD5Sum< ::mirte_msgs_2::GetKeypadRequest> should match
// service_traits::MD5Sum< ::mirte_msgs_2::GetKeypad >
template<>
struct MD5Sum< ::mirte_msgs_2::GetKeypadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs_2::GetKeypad >::value();
  }
  static const char* value(const ::mirte_msgs_2::GetKeypadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs_2::GetKeypadRequest> should match
// service_traits::DataType< ::mirte_msgs_2::GetKeypad >
template<>
struct DataType< ::mirte_msgs_2::GetKeypadRequest>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs_2::GetKeypad >::value();
  }
  static const char* value(const ::mirte_msgs_2::GetKeypadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mirte_msgs_2::GetKeypadResponse> should match
// service_traits::MD5Sum< ::mirte_msgs_2::GetKeypad >
template<>
struct MD5Sum< ::mirte_msgs_2::GetKeypadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs_2::GetKeypad >::value();
  }
  static const char* value(const ::mirte_msgs_2::GetKeypadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs_2::GetKeypadResponse> should match
// service_traits::DataType< ::mirte_msgs_2::GetKeypad >
template<>
struct DataType< ::mirte_msgs_2::GetKeypadResponse>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs_2::GetKeypad >::value();
  }
  static const char* value(const ::mirte_msgs_2::GetKeypadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MIRTE_MSGS_2_MESSAGE_GETKEYPAD_H
