// Generated by gencpp from file mirte_msgs_2/SetLEDValue.msg
// DO NOT EDIT!


#ifndef MIRTE_MSGS_2_MESSAGE_SETLEDVALUE_H
#define MIRTE_MSGS_2_MESSAGE_SETLEDVALUE_H

#include <ros/service_traits.h>


#include <mirte_msgs_2/SetLEDValueRequest.h>
#include <mirte_msgs_2/SetLEDValueResponse.h>


namespace mirte_msgs_2
{

struct SetLEDValue
{

typedef SetLEDValueRequest Request;
typedef SetLEDValueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetLEDValue
} // namespace mirte_msgs_2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mirte_msgs_2::SetLEDValue > {
  static const char* value()
  {
    return "42048ea920ba4286ecdfb4bc68063c32";
  }

  static const char* value(const ::mirte_msgs_2::SetLEDValue&) { return value(); }
};

template<>
struct DataType< ::mirte_msgs_2::SetLEDValue > {
  static const char* value()
  {
    return "mirte_msgs_2/SetLEDValue";
  }

  static const char* value(const ::mirte_msgs_2::SetLEDValue&) { return value(); }
};


// service_traits::MD5Sum< ::mirte_msgs_2::SetLEDValueRequest> should match
// service_traits::MD5Sum< ::mirte_msgs_2::SetLEDValue >
template<>
struct MD5Sum< ::mirte_msgs_2::SetLEDValueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs_2::SetLEDValue >::value();
  }
  static const char* value(const ::mirte_msgs_2::SetLEDValueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs_2::SetLEDValueRequest> should match
// service_traits::DataType< ::mirte_msgs_2::SetLEDValue >
template<>
struct DataType< ::mirte_msgs_2::SetLEDValueRequest>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs_2::SetLEDValue >::value();
  }
  static const char* value(const ::mirte_msgs_2::SetLEDValueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mirte_msgs_2::SetLEDValueResponse> should match
// service_traits::MD5Sum< ::mirte_msgs_2::SetLEDValue >
template<>
struct MD5Sum< ::mirte_msgs_2::SetLEDValueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs_2::SetLEDValue >::value();
  }
  static const char* value(const ::mirte_msgs_2::SetLEDValueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs_2::SetLEDValueResponse> should match
// service_traits::DataType< ::mirte_msgs_2::SetLEDValue >
template<>
struct DataType< ::mirte_msgs_2::SetLEDValueResponse>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs_2::SetLEDValue >::value();
  }
  static const char* value(const ::mirte_msgs_2::SetLEDValueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MIRTE_MSGS_2_MESSAGE_SETLEDVALUE_H
