// Generated by gencpp from file mirte_msgs_2/SetPinValue.msg
// DO NOT EDIT!


#ifndef MIRTE_MSGS_2_MESSAGE_SETPINVALUE_H
#define MIRTE_MSGS_2_MESSAGE_SETPINVALUE_H

#include <ros/service_traits.h>


#include <mirte_msgs_2/SetPinValueRequest.h>
#include <mirte_msgs_2/SetPinValueResponse.h>


namespace mirte_msgs_2
{

struct SetPinValue
{

typedef SetPinValueRequest Request;
typedef SetPinValueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPinValue
} // namespace mirte_msgs_2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mirte_msgs_2::SetPinValue > {
  static const char* value()
  {
    return "ca22cfaaa89cb1d56388f4014610ebb5";
  }

  static const char* value(const ::mirte_msgs_2::SetPinValue&) { return value(); }
};

template<>
struct DataType< ::mirte_msgs_2::SetPinValue > {
  static const char* value()
  {
    return "mirte_msgs_2/SetPinValue";
  }

  static const char* value(const ::mirte_msgs_2::SetPinValue&) { return value(); }
};


// service_traits::MD5Sum< ::mirte_msgs_2::SetPinValueRequest> should match
// service_traits::MD5Sum< ::mirte_msgs_2::SetPinValue >
template<>
struct MD5Sum< ::mirte_msgs_2::SetPinValueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs_2::SetPinValue >::value();
  }
  static const char* value(const ::mirte_msgs_2::SetPinValueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs_2::SetPinValueRequest> should match
// service_traits::DataType< ::mirte_msgs_2::SetPinValue >
template<>
struct DataType< ::mirte_msgs_2::SetPinValueRequest>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs_2::SetPinValue >::value();
  }
  static const char* value(const ::mirte_msgs_2::SetPinValueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mirte_msgs_2::SetPinValueResponse> should match
// service_traits::MD5Sum< ::mirte_msgs_2::SetPinValue >
template<>
struct MD5Sum< ::mirte_msgs_2::SetPinValueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs_2::SetPinValue >::value();
  }
  static const char* value(const ::mirte_msgs_2::SetPinValueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs_2::SetPinValueResponse> should match
// service_traits::DataType< ::mirte_msgs_2::SetPinValue >
template<>
struct DataType< ::mirte_msgs_2::SetPinValueResponse>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs_2::SetPinValue >::value();
  }
  static const char* value(const ::mirte_msgs_2::SetPinValueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MIRTE_MSGS_2_MESSAGE_SETPINVALUE_H
