// Generated by gencpp from file mirte_msgs_2/SetSingleLEDValue.msg
// DO NOT EDIT!


#ifndef MIRTE_MSGS_2_MESSAGE_SETSINGLELEDVALUE_H
#define MIRTE_MSGS_2_MESSAGE_SETSINGLELEDVALUE_H

#include <ros/service_traits.h>


#include <mirte_msgs_2/SetSingleLEDValueRequest.h>
#include <mirte_msgs_2/SetSingleLEDValueResponse.h>


namespace mirte_msgs_2
{

struct SetSingleLEDValue
{

typedef SetSingleLEDValueRequest Request;
typedef SetSingleLEDValueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetSingleLEDValue
} // namespace mirte_msgs_2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mirte_msgs_2::SetSingleLEDValue > {
  static const char* value()
  {
    return "4d6f4830182c46665b9a704973ece68d";
  }

  static const char* value(const ::mirte_msgs_2::SetSingleLEDValue&) { return value(); }
};

template<>
struct DataType< ::mirte_msgs_2::SetSingleLEDValue > {
  static const char* value()
  {
    return "mirte_msgs_2/SetSingleLEDValue";
  }

  static const char* value(const ::mirte_msgs_2::SetSingleLEDValue&) { return value(); }
};


// service_traits::MD5Sum< ::mirte_msgs_2::SetSingleLEDValueRequest> should match
// service_traits::MD5Sum< ::mirte_msgs_2::SetSingleLEDValue >
template<>
struct MD5Sum< ::mirte_msgs_2::SetSingleLEDValueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs_2::SetSingleLEDValue >::value();
  }
  static const char* value(const ::mirte_msgs_2::SetSingleLEDValueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs_2::SetSingleLEDValueRequest> should match
// service_traits::DataType< ::mirte_msgs_2::SetSingleLEDValue >
template<>
struct DataType< ::mirte_msgs_2::SetSingleLEDValueRequest>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs_2::SetSingleLEDValue >::value();
  }
  static const char* value(const ::mirte_msgs_2::SetSingleLEDValueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mirte_msgs_2::SetSingleLEDValueResponse> should match
// service_traits::MD5Sum< ::mirte_msgs_2::SetSingleLEDValue >
template<>
struct MD5Sum< ::mirte_msgs_2::SetSingleLEDValueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs_2::SetSingleLEDValue >::value();
  }
  static const char* value(const ::mirte_msgs_2::SetSingleLEDValueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs_2::SetSingleLEDValueResponse> should match
// service_traits::DataType< ::mirte_msgs_2::SetSingleLEDValue >
template<>
struct DataType< ::mirte_msgs_2::SetSingleLEDValueResponse>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs_2::SetSingleLEDValue >::value();
  }
  static const char* value(const ::mirte_msgs_2::SetSingleLEDValueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MIRTE_MSGS_2_MESSAGE_SETSINGLELEDVALUE_H
