// Generated by gencpp from file mirte_msgs_2/Turn.msg
// DO NOT EDIT!


#ifndef MIRTE_MSGS_2_MESSAGE_TURN_H
#define MIRTE_MSGS_2_MESSAGE_TURN_H

#include <ros/service_traits.h>


#include <mirte_msgs_2/TurnRequest.h>
#include <mirte_msgs_2/TurnResponse.h>


namespace mirte_msgs_2
{

struct Turn
{

typedef TurnRequest Request;
typedef TurnResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Turn
} // namespace mirte_msgs_2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mirte_msgs_2::Turn > {
  static const char* value()
  {
    return "55b88347e6bff17eb9eddc282d36da9d";
  }

  static const char* value(const ::mirte_msgs_2::Turn&) { return value(); }
};

template<>
struct DataType< ::mirte_msgs_2::Turn > {
  static const char* value()
  {
    return "mirte_msgs_2/Turn";
  }

  static const char* value(const ::mirte_msgs_2::Turn&) { return value(); }
};


// service_traits::MD5Sum< ::mirte_msgs_2::TurnRequest> should match
// service_traits::MD5Sum< ::mirte_msgs_2::Turn >
template<>
struct MD5Sum< ::mirte_msgs_2::TurnRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs_2::Turn >::value();
  }
  static const char* value(const ::mirte_msgs_2::TurnRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs_2::TurnRequest> should match
// service_traits::DataType< ::mirte_msgs_2::Turn >
template<>
struct DataType< ::mirte_msgs_2::TurnRequest>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs_2::Turn >::value();
  }
  static const char* value(const ::mirte_msgs_2::TurnRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mirte_msgs_2::TurnResponse> should match
// service_traits::MD5Sum< ::mirte_msgs_2::Turn >
template<>
struct MD5Sum< ::mirte_msgs_2::TurnResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mirte_msgs_2::Turn >::value();
  }
  static const char* value(const ::mirte_msgs_2::TurnResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mirte_msgs_2::TurnResponse> should match
// service_traits::DataType< ::mirte_msgs_2::Turn >
template<>
struct DataType< ::mirte_msgs_2::TurnResponse>
{
  static const char* value()
  {
    return DataType< ::mirte_msgs_2::Turn >::value();
  }
  static const char* value(const ::mirte_msgs_2::TurnResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MIRTE_MSGS_2_MESSAGE_TURN_H
