  base_width: 0.14
  base_len: 0.21081
  base_height: 0.05
  base_mass: 1

  wheel_radius: 0.0325
  wheel_mass: 0.1
  wheel_center_x_offset: 0.013805
  wheel_center_y_offset: 0.08385
  wheel_center_z_offset: -0.0075

  caster_wheel_radius: 0.005
  caster_wheel_center_x_offset: -0.085715
  caster_wheel_center_y_offset: 0
  caster_wheel_center_z_offset: -0.035
  caster_wheel_mass: 0.02
