---
ros_control_namespace: /arm/rrbot_hardware_interface
controller_list:
  - name: arm/position_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints: [shoulder, arm, arm2, gripper_joint]
